version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.4.12-alpine
    working directory: ~/DjangoRestApisPostgresSQL
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{.Branch }}-{{ checksum "requirements.txt"}}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{checksum "requirements.txt" }}
          paths:
            - "venv"
        -run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
        - store_artifacts:
            path: test-reports/
            destination: python_app
#      - run: pip install -r requirements.txt
#      - run:
#          name: connecting to postgres database
#          command: psql -h ${}